services:
  asrpri-server:
    image: asrpri:latest
    container_name: asrpri
    build: .
    ports:
      - "8300:8000"
    restart: unless-stopped
    environment:
      - TMP_DIR=/app/tmp
      - SENSEVOICE_DEVICE=cpu #cuda:0