services:
  asrpri-server:
    image: sensevoice-server:latest
    container_name: asrpri
    build: .
    ports:
      - "8300:8000"
    restart: always
    volumes:
      - type: volume
        source: TTD-Data
        target: /root/.cache
        volume:
          nocopy: true
          subpath: cosy-voice/.cache
    environment:
      - TMP_DIR=/app/tmp
      - SENSEVOICE_DEVICE=cpu #cuda:0

volumes:
  TTD-Data:
    external: true
