---
- name: Deploy SenseVoice APP to servers
  hosts: "{{ target_hosts | default('sensevoice_servers') }}"
  become: yes
  vars:
    deploy_type: "{{ deploy_type | default('standard') }}"
  roles:
    - sensevoice
